;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_001",DevComment="첫째 형 돌 사진 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_002",DevComment="여동생과 노는 일상사진 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_003",DevComment="가족 사진 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_004",DevComment="일기장 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_005",DevComment="고데기 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_015",DevComment="보조배터리 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_016",DevComment="디퓨저 쪽지 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_017",DevComment="디퓨저 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_019",DevComment="장롱 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_020",DevComment="장롱 쪽지 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_021",DevComment="책상 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_022",DevComment="자격증 책 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_023",DevComment="전신거울 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_024",DevComment="바닥 쪽지 촬영 완료")
+GameplayTagList=(Tag="Evidence.Photographed.OBJ_01_025",DevComment="책장 쪽지 촬영 완료")
+GameplayTagList=(Tag="Evidence.SentenceSolved.OBJ_01_003",DevComment="가족 사진 빈칸 문장 완성")
+GameplayTagList=(Tag="Evidence.SentenceSolved.OBJ_01_004",DevComment="일기장 빈칸 문장 완성")
+GameplayTagList=(Tag="Evidence.SentenceSolved.OBJ_01_005",DevComment="고데기 빈칸 문장 완성")
+GameplayTagList=(Tag="Evidence.SentenceSolved.OBJ_01_015",DevComment="보조배터리 빈칸 문장 완성")
+GameplayTagList=(Tag="Evidence.SentenceSolved.OBJ_01_016",DevComment="디퓨저 쪽지 빈칸 문장 완성")
+GameplayTagList=(Tag="Story.Chapter.01",DevComment="")
+GameplayTagList=(Tag="Test.Clue.Bloodstain.Found",DevComment="Story state subsystem automation test tag")
+GameplayTagList=(Tag="Test.Clue.Bloodstain.Photographed",DevComment="Story state subsystem automation test tag")
+GameplayTagList=(Tag="Test.Story.Search",DevComment="Story state subsystem automation test tag")

